// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // El Postgres local de `prisma dev` no permite crear bases al vuelo,
    // así que le indicamos su servidor "sombra" (necesario para migraciones).
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
